interface BaseBot {
    /**
     * The bot's slug, used in the subdomain.
     */
    slug: string;
    /**
     * The bot's numeric user ID on Discord.
     */
    id: number;
    /**
     * The bot's name.
     */
    name: string;
    /**
     * A short description of the bot. Markdown is supported.
     */
    short_description: string;
    /**
     * The ID of the page containing the bot's long description. Should be autogenerated.
     */
    page_id: number | null;
    /**
     * The bot's default permissions to use in the invite URL.
     */
    permissions: number;
    /**
     * When the bot's record was created on the website.
     */
    created_at: Date;
    /**
     * When the bot's record was last updated on the website.
     */
    updated_at: Date;
}

export interface Bot extends BaseBot {
    /**
     * The bot's prefix(es).
     */
    prefix: string[] | null;
}

export interface InsertBot extends BaseBot {
    /**
     * Inserting an array requires stringification.
     */
    prefix: string | null;
}
